In [3]:
"""
    0,1及指定张量的创建
    0张量:张量元素全部是0的张量.方法=====>torch.zeros() 或者是:torch.zeros_like()
    1张量:张量元素全部是1的张量.方法=====>torch.ones() 或者是:torch.ones_like()
    指定张量:张量元素是某一指定值的张量:方法====>torch.full() 或者是toe吃.full_like()
"""


'\n    0,1及指定张量的创建\n    0张量:张量元素全部是0的张量.方法=====>torch.zeros() 或者是:torch.zeros_like()\n    1张量:张量元素全部是1的张量.方法=====>torch.ones() 或者是:torch.ones_like()\n    指定张量:张量元素是某一指定值的张量:方法====>torch.full() 或者是toe吃.full_like()\n'

In [2]:
import torch

In [8]:
# 0张量
torch.zeros(2,3)
t1=torch.zeros(4,5)
torch.zeros_like(t1)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [11]:
# 1张量
torch.ones(2,3)
t2=torch.ones(4,5)
torch.ones_like(t2)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
# 指定张量
torch.full([2,3],5)
"""
    full创建张量参数说明:
    参数1:[2,3]指定张量形状
    参数2:5 指定张量值
"""

t3=torch.full([4,5],6)
torch.full_like(t3,7)



tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])