# 创建线性张量

In [4]:
import torch
import numpy as np

In [6]:
# torch.arange(start, end, step)
print(torch.arange(1,10))
print(torch.arange(1,10,2))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 3, 5, 7, 9])


In [8]:
# torch.linspace(start, end, steps)
print(torch.linspace(1,10,5))  # 等差数列张量
print(torch.linspace(1,10,5,dtype=torch.int64))

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([ 1,  3,  5,  7, 10])


In [34]:
# 设置和获取随机种子
# 设置随机种子
torch.random.manual_seed(100)

print(torch.rand(2, 3))
print(torch.rand(2, 3))
"""
    执行结果:
    tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
    tensor([[0.2627, 0.0428, 0.2080],
            [0.1180, 0.1217, 0.7356]])
    结论:设置了随机种子之后,无论运行上述代码多少次,结果都是不变的
"""

# 获取设置的随机种子

print(torch.random.initial_seed()) # 获取100上面设置的随机种子


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
100


In [42]:
# 随机张量
print(torch.rand(2, 3)) # 随机两行三列的浮点数张量
print(torch.randn(2, 3)) # 随机两行三列的浮点数张量

"""
     randint随机两行三列的整型张量
     参数1: 最小值
     参数2:最大值(取不到)
     参数3:形状

"""
print(torch.randint(5, 10, (2, 3))) 
 

tensor([[0.3436, 0.2028, 0.9792],
        [0.4947, 0.3617, 0.9687]])
tensor([[-0.4917,  2.0574, -1.5916],
        [-0.0928,  1.9353, -0.3017]])
tensor([[5, 6, 9],
        [8, 7, 8]])
