# 张量类型转换

In [1]:
import torch

In [8]:
t1=torch.tensor([1,2,3],dtype=torch.int32)
print(t1.detach().clone().half()) #tensor([1., 2., 3.], dtype=torch.float16)
print(t1.detach().clone().float()) #tensor([1., 2., 3.])
print(t1.detach().clone().double()) # tensor([1., 2., 3.], dtype=torch.float64)
print(t1.detach().clone().long()) # tensor([1, 2, 3])
print(t1.detach().clone().short()) # tensor([1, 2, 3], dtype=torch.int16)
"""
    detach().clone() 可以保留张量的梯度信息并复制数据,不会导致警告
"""

tensor([1., 2., 3.], dtype=torch.float16)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.int16)
