# 张量创建

In [ ]:
import numpy as np
import torch

In [7]:
print(torch.tensor(10))

tensor(10)


In [9]:
print(torch.tensor([1,2,3]))

tensor([1, 2, 3])


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(torch.tensor(arr))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
print(torch.Tensor(10))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [15]:
print(torch.Tensor([1,2,3]))

tensor([1., 2., 3.])


In [16]:
print(torch.Tensor(arr))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
