# numpy入门

## numpy学习案例

In [ ]:
#导入munpy
import numpy as np

In [ ]:
"""
    numpy创建数组并调用对应属性
"""
arr=np.arange(0,15,dtype=int).reshape(3,5)
print(f"数组结构：{arr}")
print(f"数组每个元素的大小{arr.itemsize}")
print(f"数组的形状：行列{arr.shape}")
print(f"数组的维度(轴):{arr.ndim}")
print(f"数组的元素类型：{arr.dtype}")
print(f"数组的类型：{type(arr)}")
print(f"数组的长度：{arr.size}")

## 属性对象说明


**reshape** : 数组形状，主要指几行几列数组

**itemsize**:数组每个元素的大小

**ndim**:数组的轴，也叫数组的维度

**dtype**:数组的元素类型。主要取值有int,float等

**size**:数组的长度

**type(数组)**:数组的类型

## numpy创建数组

- 使用array()方法创建

In [ ]:
# 使用array()方法创建数组
# 参数是列表形式（numpy可以将列表转化为数组）
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr1)
print(f"数组类型{type(arr1)}")
print(f"数组长度{arr1.size}")
print(f"数组的元素类型{arr1.dtype}")
print(f"数组的元素大小{arr1.itemsize}")


- 使用arange()方法创建

In [ ]:
# 使用arange()方法创建数组对象
# arange参数说明:依次分别是：起始值，结束值和步长
arr2=np.arange(2,10,2,dtype=np.int32).reshape(2,2)
print(arr1)
print(f"数组类型{type(arr2)}")
print(f"数组长度{arr2.size}")
print(f"数组的元素类型{arr2.dtype}")
print(f"数组的元素大小{arr2.itemsize}")

- 创建随机数数组

In [ ]:
# 创建随机数整数数组对象
arr3=np.random.randint(0,9,size=(3,3),dtype=np.int64)
print(arr3)
print(f"数组类型{type(arr3)}")
print(f"数组长度{arr3.size}")
print(f"数组的元素类型{arr3.dtype}")
print(f"数组的元素大小{arr3.itemsize}")

In [ ]:
# 创建随机数小数数组
arr4=np.random.uniform(-1,7,size=(3,3))
print(arr4)
print(f"小数数组类型{type(arr4)}")
print(f"小数数组长度{arr4.size}")
print(f"小数数组的元素类型{arr4.dtype}")
print(f"小数数组的元素大小{arr4.itemsize}")

## ndarray类型转换

In [39]:
#ndarray类型转换,通过数组的astype属性去转化，参数是转化的目标类型
#arr4 是类型为float64的小数数组
arr5=arr4.astype(np.float32)
print(arr5)
print(f"转换后的数据类型是：{arr5.dtype}")

[[ 4.2879605   2.7306256   1.8674185 ]
 [ 0.8038859  -0.2233167  -0.32282415]
 [ 5.3197436   3.324704    6.3644004 ]]
转换后的数据类型是：float32


## 等比数列 logspace

In [41]:
# 等比数列使用logspace表示
# np.logspace(起始次幂，结束次幂，长度，base=基数) **默认的基础不写时为10
# eg: 在2的0次幂到2的8次幂之间取长度为10的等比数列。基础为2
arr6=np.logspace(0,8,10,base=2)
print(arr6)

[  1.           1.85174942   3.42897593   6.34960421  11.75787594
  21.77264     40.3174736   74.65785853 138.24764658 256.        ]


## 等差数列 linspace

In [43]:
# 等差数列使用linspace表示
# linspace(起始值，结束值，长度， endpoint=True) endpoint指是否包含结束值，默认是True包含结束值，设置为False可不包含结束值
arr7=np.linspace(1,10,10)
print(arr7)


# 等差数列不包含结束值的形式
arr8=np.linspace(1,10,10,endpoint=False)
print(arr8)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
