# 张量的形状操作

In [14]:
import torch
torch.manual_seed(100)

In [15]:
t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape)
t1

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# 改变张量的形状
t2=t1.reshape(3,2)
t3=t1.reshape(-1)
t3

tensor([1, 2, 3, 4, 5, 6])

In [34]:
t4=t1.unsqueeze(dim=0)
print(t4)
# t4 在0维增加一维 
[
  [
    [1, 2, 3],
    [4, 5, 6]
  ]
]
t4.size()

tensor([[[1, 2, 3],
         [4, 5, 6]]])


torch.Size([1, 2, 3])

In [33]:
t5=t1.unsqueeze(dim=1)
print(t5)

# t5 列增加一个维度
[
  [
    [1, 2, 3]
  ],

  [
    [4, 5, 6]
  ]
]

t5.size()


tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


torch.Size([2, 1, 3])

In [36]:
t6=torch.randint(0,10,(2,1,3,1))
print(t6)
t6.size()

tensor([[[[2],
          [8],
          [8]]],


        [[[0],
          [4],
          [3]]]])


torch.Size([2, 1, 3, 1])

In [ ]:
# squeeze删除所有维度为1的维
t7=t6.squeeze()
t7

tensor([[2, 8, 8],
        [0, 4, 3]])