In [ ]:
"""
    1. 掌握简单行列索引的使用
    2. 掌握列表索引的使用
    3. 掌握范围索引的使用
    4. 知道布尔索引的使用
    5. 知道多维索引的使用
"""

In [23]:
import torch

torch.manual_seed(666)

In [24]:
# 行列索引的使用
# 索引表达式:张量[行,列]
t1 = torch.randint(0, 10, (3, 4))
print(t1)
print(t1[0, 1])  #  取第一行第二列的值
print(t1[1, :])  # 取第二行所有值
print(t1[:, 1])  # 取第二列所有制

tensor([[0, 4, 9, 8],
        [4, 2, 7, 0],
        [4, 7, 5, 4]])
tensor(4)
tensor([4, 2, 7, 0])
tensor([4, 2, 7])


In [27]:
t1 = torch.randint(0, 10, (2, 3, 4))
print(t1)  # 张量维度:2个3行四列
t1[0, 1, 2]  # 取第一块,第二行第三列的值

tensor([[[0, 7, 6, 5],
         [9, 6, 8, 3],
         [1, 0, 6, 3]],

        [[8, 7, 3, 4],
         [9, 5, 3, 1],
         [2, 4, 1, 2]]])


tensor(8)